const x = 10

try {
x = 2
}
catch (error) {

      console.log('X Não é um inteiro')
}